name:                 csp-language
version:              0.1.0.0
visibility:           public
id:                   csp-language-0.1.0.0-inplace
key:                  csp-language-0.1.0.0-inplace
license:              MIT
abi:                  inplace
exposed:              True
exposed-modules:      CSP.AST CSP.Parser CSP.Solver
import-dirs:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\build"

library-dirs:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\build"
    C:\ghcup\msys64\mingw64\lib

data-dir:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\."

hs-libraries:         HScsp-language-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.18.3.0 containers-0.6.7
haddock-interfaces:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\doc\\html\\csp-language\\csp-language.haddock"

haddock-html:
    "C:\\Arsen\\WUT\\Subjects\\Semester 6.2\\Functional Programming\\Haskell-Course-2026\\project\\dist-newstyle\\build\\x86_64-windows\\ghc-9.6.7\\csp-language-0.1.0.0\\doc\\html\\csp-language"
